/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as CrmSlugRouteImport } from './routes/crm.$slug'
import { Route as CrmSlugIndexRouteImport } from './routes/crm.$slug.index'
import { Route as CrmSlugSectionRouteImport } from './routes/crm.$slug.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSlugRoute = CrmSlugRouteImport.update({
  id: '/crm/$slug',
  path: '/crm/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSlugIndexRoute = CrmSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmSlugRoute,
} as any)
const CrmSlugSectionRoute = CrmSlugSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => CrmSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/reports': typeof ReportsRoute
  '/training': typeof TrainingRoute
  '/crm/$slug': typeof CrmSlugRouteWithChildren
  '/crm/$slug/$section': typeof CrmSlugSectionRoute
  '/crm/$slug/': typeof CrmSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/reports': typeof ReportsRoute
  '/training': typeof TrainingRoute
  '/crm/$slug/$section': typeof CrmSlugSectionRoute
  '/crm/$slug': typeof CrmSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/reports': typeof ReportsRoute
  '/training': typeof TrainingRoute
  '/crm/$slug': typeof CrmSlugRouteWithChildren
  '/crm/$slug/$section': typeof CrmSlugSectionRoute
  '/crm/$slug/': typeof CrmSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/reports'
    | '/training'
    | '/crm/$slug'
    | '/crm/$slug/$section'
    | '/crm/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/reports'
    | '/training'
    | '/crm/$slug/$section'
    | '/crm/$slug'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/reports'
    | '/training'
    | '/crm/$slug'
    | '/crm/$slug/$section'
    | '/crm/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ReportsRoute: typeof ReportsRoute
  TrainingRoute: typeof TrainingRoute
  CrmSlugRoute: typeof CrmSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/$slug': {
      id: '/crm/$slug'
      path: '/crm/$slug'
      fullPath: '/crm/$slug'
      preLoaderRoute: typeof CrmSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/$slug/': {
      id: '/crm/$slug/'
      path: '/'
      fullPath: '/crm/$slug/'
      preLoaderRoute: typeof CrmSlugIndexRouteImport
      parentRoute: typeof CrmSlugRoute
    }
    '/crm/$slug/$section': {
      id: '/crm/$slug/$section'
      path: '/$section'
      fullPath: '/crm/$slug/$section'
      preLoaderRoute: typeof CrmSlugSectionRouteImport
      parentRoute: typeof CrmSlugRoute
    }
  }
}

interface CrmSlugRouteChildren {
  CrmSlugSectionRoute: typeof CrmSlugSectionRoute
  CrmSlugIndexRoute: typeof CrmSlugIndexRoute
}

const CrmSlugRouteChildren: CrmSlugRouteChildren = {
  CrmSlugSectionRoute: CrmSlugSectionRoute,
  CrmSlugIndexRoute: CrmSlugIndexRoute,
}

const CrmSlugRouteWithChildren =
  CrmSlugRoute._addFileChildren(CrmSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ReportsRoute: ReportsRoute,
  TrainingRoute: TrainingRoute,
  CrmSlugRoute: CrmSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
